dataset_name: hacs
train_split: [ 'training' ]
val_split: [ 'validation' ]
dataset: {
  json_file: /home/ubuntu/disk1/Even/code/SlowFast/even/notebook/slowfast_data.json,
  # /home/ubuntu/disk1/Even/code/SlowFast/even/notebook/slowfast_data.json,
  # ./data/hacs/annotations/HACS_segments_v1.1.1_slowfast.json,
  feat_folder: /home/ubuntu/disk1/Even/Dataset/slowfast_cholec80_2,
  # /home/ubuntu/disk1/Even/Dataset/slowfast_cholec80,
  # /home/ubuntu/disk1/Even/Dataset/hacs/slowfast_feature,
  file_ext: .npy,
    # .pkl,
    # .npy,
  num_classes: 7,
    # 200,
    # 7,
  input_dim: 2304,
  feat_stride: 4,
  num_frames: 1,
  default_fps: 1,
    # 1,
  trunc_thresh: 0.5,
  # crop_ratio: 随机的特征裁剪
  crop_ratio: [ 0.9, 1.0 ],
  # [ 0.9, 1.0 ],
  max_seq_len: 2304,
    # 960,
    # 2304,
  backbone_type: 'slowfast',
  # downsample_rate: 8,
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 1.0,
  # backbone_type: conv,        # 如果替换成conv结构，里面结构的参数还不知道怎么设置的
  backbone_arch: [ 2, 2, 5 ],   # 前面两个数字不知道表示什么意思的
  n_sgp_win_size: 3,
  regression_range: [ [ 0, 4 ], [ 4, 8 ], [ 8, 16 ], [ 16, 32 ], [ 32, 64 ], [ 64, 10000 ] ],
  embd_dim: 1024,               # 这几个dim是否有可以调整的可能？原论文里面没有关于dim的参数，Tridet论文需要再看一遍是否有消融实验还是单纯的经验设置？
  sgp_mlp_dim: 1024,
  fpn_dim: 1024,
  head_dim: 1024,
  head_kernel_size: 5,
  boudary_kernel_size: 1,
  use_abs_pe: True,
  num_bins: 15,                 # 这个bin是指一边的bin，不知道是否需要调整。
  iou_weight_power: 1,
  input_noise: 0.2,
  use_trident_head: True,
  k: 1.2,
  init_conv_vars: 0.1,
}
opt: {
  learning_rate: 0.001,
  eta_min: 0.0005,
  warmup_epochs: 10,
  epochs: 90,
  weight_decay: 0.03,
}
loader: {
  batch_size: 6,
}
train_cfg: {
  init_loss_norm: 400,
  clip_grad_l2norm: 0.5,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  label_smoothing: 0.1,
}

# similar to THUMOS
test_cfg: {
  voting_thresh: 0.95,
  pre_nms_topk: 2000,
  max_seg_num: 250,         # 这个参数有什么特殊的意义吗？
  min_score: 0.001,
  multiclass_nms: True,
  nms_sigma: 0.75,
}
output_folder: ./ckpt_2/
resume: True


# 如何调整AP计算的范围
# 如何计算最后的准确率，以及实现可视化
# 里面虽然有

