dataset_name: thumos
train_split: [ 'training' ]
val_split: [ 'validation' ]
dataset: {
  json_file: /home/ubuntu/disk1/Even/code/SlowFast/even/notebook/slowfast_data.json,
  feat_folder: /home/ubuntu/disk1/Even/Dataset/ViT_feature,
  # ./data/thumos/i3d_features,
  file_prefix: ~,
  file_ext: .npy,
  num_classes: 7,
  input_dim: 768,
  feat_stride: 1,
  num_frames: 1,
  default_fps: 1,
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [ 0.9, 1.0 ],
  # crop_ratio 这个参数会让训练集进行随机裁剪，每次获取到的数据都是不一样的
  max_seq_len: 6144,
  # 这个 max_seq_len 可能得满足某个要求？之前6000不行，改成6114可以了
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 6.0,
  # backbone_type: conv,
  backbone_arch: [ 2, 2, 6 ],
  n_sgp_win_size: 3,
  regression_range: [ [ 0, 4 ], [ 4, 8 ], [ 8, 16 ], [ 16, 32 ], [ 32, 64 ], [ 64, 128 ], [ 128, 10000 ] ],
  num_bins: 15,
  # embd_dim: 1024,               # 这几个dim是否有可以调整的可能？原论文里面没有关于dim的参数，Tridet论文需要再看一遍是否有消融实验还是单纯的经验设置？
  sgp_mlp_dim: 768,
  # fpn_dim: 1024,
  # head_dim: 1024,
  head_kernel_size: 5,
  iou_weight_power: 0.1,
  use_trident_head: True,
  input_noise: 0.2
}
opt: {
  learning_rate: 0.001,
  eta_min: 0.0005,
  warmup_epochs: 10,
  epochs: 190,
  weight_decay: 0.03,
}
loader: {
  batch_size: 6,
}
train_cfg: {
  init_loss_norm: 400,
  clip_grad_l2norm: 0.5,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  label_smoothing: 0.1,
}
# the inference on THUMOS is quite different from EPIC-kitchens
# a major performance gain is achieved by fusing external classification scores
# doing so will require disable multiclass_nms and enable score fusion
test_cfg: {
  voting_thresh: 0.95,
  pre_nms_topk: 2000,
  max_seg_num: 250,         # 这个参数有什么特殊的意义吗？
  min_score: 0.001,
  multiclass_nms: True,
  nms_sigma: 0.75,
}
output_folder: ./ckpt_ViT/

